[package]
name = "ndcopy"
description = "Fast N-dimensional array memcpy"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bonsairobo/ndcopy-rs"
keywords = ["array", "tensor"]

[dependencies]
ndshape = "0.2"
