[package]
name = "ndcopy"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bonsairobo/ndcopy-rs"
keywords = ["array", "tensor"]

[dependencies]
ndshape = "0.1"
